### PR TITLE
Carter Plunging Fix

### PR DESCRIPTION
**Pull request by fjebaker**
Along with
- https://github.com/astro-group-bristol/CarterBoyerLindquist.jl/pull/5
this now fixes calculation errors in the plunging region redshift.

## Plots
For `M=1.0`, `a=-1.0` at tolerance `1e-9`:

redshift-2nd-order-1

redshift-carter-1

redshift-difference

### CODE REVIEW

**Comment by fjebaker** [comment]
Fixes #18

**Comment by phajy** [comment]
Can you add a contour that shows the ISCO (r =~ 9 r_g in this case)? I'd expect g to drop inside the ISCO on the near side as the radial velocity increases. (Apologies for jumping in mid-conversation; might be misinterpreting the figures!)

**Comment by fjebaker** [comment]
@phajy I wasn't convinced by this plots either, which is why I've left the PR unmerged...

With the ISCO contour:

isco-contour

There's a slight convention error that I noticed last week, which may be causing this:
- https://github.com/astro-group-bristol/GeodesicBase.jl/pull/4

Switching the direction of the `r` component of the velocity (and in Carter's method, the sign of the radial potential) when calculating the redshift yields:

isco-2

**Comment by fjebaker** [comment]
The only problem is that doesn't _feel_ right:

The current **photon velocity** vector for the redshift is the reverse of the calculated 4-vector, since we trace _backwards_ through time, but calculate _forwards_.

https://github.com/astro-group-bristol/AccretionFormulae.jl/blob/d784a62832753b870d2cf881c52de9c943079a77/src/redshift.jl#L176-L180

But to get the 2nd plot in my last comment requires
```julia
p = @inbounds @SVector [
    -v[1], v[2], 0, -v[4]
]
```

(and similar for the Carter method) which _feels_ like it's going the wrong way?

**Comment by phajy** [comment]
Thanks for adding the contour. I hadn't realised where the outer radius of the disk was which caused me a bit of confusion but now it is obvious! Yes, we're integrating backwards to need to reverse the photon direction but the disk gas velocity should be OK without needing to be reversed.

Ah, one other oddity I've thought of that arises from integrating backwards from the observer. A ray propagating close enough to the (spinning) black hole should co-rotate with the black hole (whichever direction it is spinning in if a = ±1). Does the symmetry of the equations change with t -> -t (e.g., do we need a -> -a or something like that)?

**Comment by fjebaker** [comment]
Updated the signs to reflect the second case -- we'll come up with a justification later, but this will at least let Dan and Kyle explore physical quantities within the ISCO for arbitrary spin.

**Pull request merged**
